# This workflow will install Python dependencies, run tests, and lint with multiple Python versions
# For more information, see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python Package CI
 {
  "true":{
    "push":{
      "branches":[
        "main"
      ]
    }, 
    "pull_request":{
      "branches":[
        "main"
      ]
    }
  }, 
  "jobs":{
    "build":{
      "runs-on":"ubuntu-latest", 
      "steps":[
        {
          "uses":"actions/checkout@v3", 
          "name":"Checkout code"
        }, 
        {
          "uses":"actions/setup-python@v3", 
          "with":{
            "python-version":"${{ matrix.python-version }}"
          }, 
          "name":"Set up Python ${{ matrix.python-version }}"
        }, 
        {
          "run":"python -m pip install --upgrade pip\npython -m pip install flake8 pytest\nif [ -f requirements.txt ]; then pip install -r requirements.txt; fi\n", 
          "name":"Install dependencies"
        }, 
        {
          "run":"# Stop the build if there are Python syntax errors or undefined names\nflake8 . --count --select=E9,F63,F7,F82 --show-source --statistics\n# Optional: Treat warnings as errors by removing the --exit-zero flag\nflake8 . --count --max-complexity=10 --max-line-length=127 --statistics\n", 
          "name": "Lint with flake8"
        }, 
        {
          "run": "pytest", 
          "name": "Run tests with pytest"
        }
      ], 
      "strategy": {
        "matrix": {
          "python-version": [
            "3.9", 
            "3.10", 
            "3.11"
          ]
        }, 
        "fail-fast":
      }
    }
  }, 
  "name": "Python Package CI"
}
